

const Content = () => {
  return (
    <div style={{ flex: 1, padding: 20 }} class="content">Content
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Senectus et netus et malesuada fames ac. Egestas quis ipsum suspendisse ultrices gravida dictum. Volutpat odio facilisis mauris sit amet massa. Elementum facilisis leo vel fringilla est ullamcorper. Tristique senectus et netus et malesuada fames ac turpis. Bibendum est ultricies integer quis auctor. At varius vel pharetra vel turpis nunc. Enim nunc faucibus a pellentesque. Ultrices vitae auctor eu augue ut lectus arcu. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Morbi tincidunt ornare massa eget egestas purus viverra accumsan. Lacus viverra vitae congue eu consequat ac felis donec et. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Et magnis dis parturient montes nascetur ridiculus. Bibendum arcu vitae elementum curabitur vitae nunc. Vitae turpis massa sed elementum tempus egestas sed sed risus. Dolor sit amet consectetur adipiscing. Aliquam ut porttitor leo a diam sollicitudin tempor id.

Feugiat sed lectus vestibulum mattis ullamcorper. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Dui id ornare arcu odio ut sem. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Massa eget egestas purus viverra accumsan in nisl nisi. Turpis tincidunt id aliquet risus. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Bibendum arcu vitae elementum curabitur vitae nunc. Nibh tortor id aliquet lectus proin nibh. Eu non diam phasellus vestibulum lorem. Facilisi morbi tempus iaculis urna id. Amet aliquam id diam maecenas ultricies mi eget mauris. Purus in mollis nunc sed. Nunc sed blandit libero volutpat sed cras ornare. Eu lobortis elementum nibh tellus molestie nunc non.

Lobortis mattis aliquam faucibus purus in massa tempor. Nibh ipsum consequat nisl vel pretium. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Nunc sed id semper risus in hendrerit gravida. Auctor neque vitae tempus quam. Tellus mauris a diam maecenas sed enim. Donec enim diam vulputate ut pharetra sit amet aliquam. Amet cursus sit amet dictum sit amet. Consequat mauris nunc congue nisi. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Amet cursus sit amet dictum sit. Diam vulputate ut pharetra sit amet. Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Habitant morbi tristique senectus et netus et malesuada. Egestas sed sed risus pretium. Eu consequat ac felis donec et. Quam pellentesque nec nam aliquam sem et tortor. At in tellus integer feugiat scelerisque. Fermentum posuere urna nec tincidunt praesent.

Sagittis nisl rhoncus mattis rhoncus urna neque. Enim facilisis gravida neque convallis a. Morbi quis commodo odio aenean sed. Fusce id velit ut tortor pretium viverra. Odio pellentesque diam volutpat commodo. Id aliquet lectus proin nibh nisl. Facilisis magna etiam tempor orci. Duis ultricies lacus sed turpis tincidunt id. Eget est lorem ipsum dolor sit amet. Diam in arcu cursus euismod quis viverra nibh. Nisl nisi scelerisque eu ultrices vitae auctor. Neque convallis a cras semper auctor neque vitae tempus.

Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Ut tristique et egestas quis ipsum. Habitant morbi tristique senectus et netus et. Purus semper eget duis at tellus at urna condimentum mattis. Mi sit amet mauris commodo. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Nibh tellus molestie nunc non. Nisl nisi scelerisque eu ultrices vitae. Id aliquet risus feugiat in ante metus dictum. Vitae justo eget magna fermentum iaculis eu non. Sit amet mattis vulputate enim nulla aliquet porttitor. Aliquet nec ullamcorper sit amet risus nullam eget. A scelerisque purus semper eget duis at tellus. Auctor neque vitae tempus quam pellentesque nec nam. Morbi non arcu risus quis varius quam quisque. Euismod nisi porta lorem mollis aliquam ut. Duis convallis convallis tellus id interdum velit.

At auctor urna nunc id cursus metus aliquam eleifend mi. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Massa vitae tortor condimentum lacinia. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vel elit scelerisque mauris pellentesque pulvinar. Platea dictumst quisque sagittis purus sit amet. Nunc id cursus metus aliquam eleifend mi in nulla posuere. Scelerisque in dictum non consectetur a. Lacus laoreet non curabitur gravida arcu ac tortor. Commodo viverra maecenas accumsan lacus vel facilisis.

Pellentesque elit eget gravida cum sociis natoque penatibus. Gravida arcu ac tortor dignissim convallis aenean et tortor. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Arcu bibendum at varius vel pharetra vel turpis nunc. Lectus magna fringilla urna porttitor rhoncus dolor. In vitae turpis massa sed elementum tempus egestas. Imperdiet sed euismod nisi porta lorem mollis. Facilisis volutpat est velit egestas dui id. Porta lorem mollis aliquam ut. Justo nec ultrices dui sapien eget mi. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Condimentum mattis pellentesque id nibh. In nulla posuere sollicitudin aliquam ultrices sagittis. Eget dolor morbi non arcu risus quis varius. Nulla porttitor massa id neque aliquam vestibulum morbi. Et malesuada fames ac turpis egestas.

In vitae turpis massa sed elementum tempus egestas sed. Consectetur lorem donec massa sapien faucibus et molestie. Lacinia at quis risus sed vulputate odio ut enim blandit. Sed turpis tincidunt id aliquet risus. At auctor urna nunc id. In fermentum et sollicitudin ac orci phasellus egestas. Nunc sed blandit libero volutpat. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Tincidunt ornare massa eget egestas purus viverra accumsan. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie.

Nibh venenatis cras sed felis eget velit aliquet sagittis id. Ac tincidunt vitae semper quis lectus nulla at volutpat. Tincidunt eget nullam non nisi est sit amet. Placerat orci nulla pellentesque dignissim enim sit amet. Lacinia at quis risus sed vulputate odio ut. Elit duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Cursus sit amet dictum sit amet justo donec enim diam. Sed sed risus pretium quam vulputate. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Senectus et netus et malesuada fames ac. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Cras fermentum odio eu feugiat pretium nibh ipsum. Vivamus at augue eget arcu dictum varius. Volutpat odio facilisis mauris sit amet.

Ullamcorper eget nulla facilisi etiam dignissim. Tristique senectus et netus et malesuada. Lectus nulla at volutpat diam ut. Consectetur adipiscing elit duis tristique sollicitudin. Ornare aenean euismod elementum nisi quis. Ultrices in iaculis nunc sed. Bibendum neque egestas congue quisque egestas diam. Urna molestie at elementum eu facilisis sed odio morbi. Morbi blandit cursus risus at ultrices mi tempus. Sagittis id consectetur purus ut. Dui sapien eget mi proin. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum.</div>
  )
}

export default Content